### PR TITLE
#34 Collections Page

### PR DESCRIPTION
**Pull request by BenBolthouse**
Added functionality on collections page to:

* View existing default collections "Have Visited" and "Want To Visit",
* Create custom collections using an "Add Collection" link,
* View custom collections,
* Navigate to spots in collections via hyperlinks.

### CODE REVIEW

**Comment by r-maloney** [comment]
The collection page looks great and the styling works well. I couple of quick things I saw: 
- There is no way to add a spot to a custom collection
- The visited/want to visit buttons don't stay consistent with what is in the database

**Review by r-maloney — APPROVED** [review]
Everything on the collections page looks good to go!

**Comment by BenBolthouse** [comment]
@r-maloney per our Slack conversation I will move bullet 2 of your feedback as acceptance criteria on issue #36 and rename accordingly. Bullet 1 is a non-issue, thanks for looking into it. Thanks!

**Comment by BenBolthouse** [comment]
🚢🚢🚢

**Pull request merged**
